// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.web;

import com.springsource.roo.inspect.domain.Device;
import com.springsource.roo.inspect.domain.DeviceInspectRec;
import com.springsource.roo.inspect.domain.InspectItem;
import com.springsource.roo.inspect.web.DeviceInspectRecController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect DeviceInspectRecController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String DeviceInspectRecController.create(@Valid DeviceInspectRec deviceInspectRec, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, deviceInspectRec);
            return "deviceinspectrecs/create";
        }
        uiModel.asMap().clear();
        deviceInspectRec.persist();
        return "redirect:/deviceinspectrecs/" + encodeUrlPathSegment(deviceInspectRec.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String DeviceInspectRecController.createForm(Model uiModel) {
        populateEditForm(uiModel, new DeviceInspectRec());
        return "deviceinspectrecs/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String DeviceInspectRecController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("deviceinspectrec", DeviceInspectRec.findDeviceInspectRec(id));
        uiModel.addAttribute("itemId", id);
        return "deviceinspectrecs/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String DeviceInspectRecController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("deviceinspectrecs", DeviceInspectRec.findDeviceInspectRecEntries(firstResult, sizeNo));
            float nrOfPages = (float) DeviceInspectRec.countDeviceInspectRecs() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("deviceinspectrecs", DeviceInspectRec.findAllDeviceInspectRecs());
        }
        return "deviceinspectrecs/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String DeviceInspectRecController.update(@Valid DeviceInspectRec deviceInspectRec, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, deviceInspectRec);
            return "deviceinspectrecs/update";
        }
        uiModel.asMap().clear();
        deviceInspectRec.merge();
        return "redirect:/deviceinspectrecs/" + encodeUrlPathSegment(deviceInspectRec.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String DeviceInspectRecController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, DeviceInspectRec.findDeviceInspectRec(id));
        return "deviceinspectrecs/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String DeviceInspectRecController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        DeviceInspectRec deviceInspectRec = DeviceInspectRec.findDeviceInspectRec(id);
        deviceInspectRec.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/deviceinspectrecs";
    }
    
    void DeviceInspectRecController.populateEditForm(Model uiModel, DeviceInspectRec deviceInspectRec) {
        uiModel.addAttribute("deviceInspectRec", deviceInspectRec);
        uiModel.addAttribute("devices", Device.findAllDevices());
        uiModel.addAttribute("inspectitems", InspectItem.findAllInspectItems());
    }
    
    String DeviceInspectRecController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
