// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.DeviceInspectRec;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect DeviceInspectRec_Roo_Jpa_Entity {
    
    declare @type: DeviceInspectRec: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long DeviceInspectRec.id;
    
    @Version
    @Column(name = "version")
    private Integer DeviceInspectRec.version;
    
    public Long DeviceInspectRec.getId() {
        return this.id;
    }
    
    public void DeviceInspectRec.setId(Long id) {
        this.id = id;
    }
    
    public Integer DeviceInspectRec.getVersion() {
        return this.version;
    }
    
    public void DeviceInspectRec.setVersion(Integer version) {
        this.version = version;
    }
    
}
