// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.Device;
import com.springsource.roo.inspect.domain.DeviceInspectRec;
import com.springsource.roo.inspect.domain.InspectItem;

privileged aspect DeviceInspectRec_Roo_JavaBean {
    
    public String DeviceInspectRec.getRvalue() {
        return this.rvalue;
    }
    
    public void DeviceInspectRec.setRvalue(String rvalue) {
        this.rvalue = rvalue;
    }
    
    public Device DeviceInspectRec.getDevice() {
        return this.device;
    }
    
    public void DeviceInspectRec.setDevice(Device device) {
        this.device = device;
    }
    
    public InspectItem DeviceInspectRec.getItem() {
        return this.item;
    }
    
    public void DeviceInspectRec.setItem(InspectItem item) {
        this.item = item;
    }
    
}
