// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.TValue;

privileged aspect TValue_Roo_JavaBean {
    
    public String TValue.getTvalue() {
        return this.tvalue;
    }
    
    public void TValue.setTvalue(String tvalue) {
        this.tvalue = tvalue;
    }
    
}
