// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.inspect.domain;

import com.springsource.roo.inspect.domain.TValue;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TValue_Roo_Configurable {
    
    declare @type: TValue: @Configurable;
    
}
